apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl: 
  # telling skaffold to watch all files in ./infra/k8s/* basically no need to run kubectl 
  # apply -f all the time you make change. Also it will delete all objects related to this directories if skaffold stops
    manifests:
      - ./infra/k8s/*
build:
  googleCloudBuild:
    projectId: ticketing-300820
  # artifact section is related to code syncing, it deployes code to the pod
  artifacts:
    - image: us.gcr.io/ticketing-300820/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
        # if change is made to below mentioned directories skaffold will replace old file with updated 
        # if change will be made to the directories other that mentioned below , it will rebuild entire image
          - src: 'src/**/*.ts'
            dest: .
    - image: us.gcr.io/ticketing-300820/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
        # if change is made to below mentioned directories skaffold will replace old file with updated 
        # if change will be made to the directories other that mentioned below , it will rebuild entire image
          - src: '**/*.js'
            dest: .
